#pragma once

enum alignment {LEFT, RIGHT, CENTER};

/* Function prototypes */
static void updateLocalTime(void);
bool getTodaysWeather(void);
bool getWeatherForecast(void);
void initialiseDisplay(void);
void displayErrorMessage(String message);
void displaySystemInfo(int x, int y);
void drawString(int x, int y, String text, alignment align);
void displayInformation(bool today_flag, bool forecast_flag);
void displayTemperature(int x, int y);
void displayCloudCover(int x, int y, int cover);
void addCloud(int x, int y, int scale, int linesize);
void displayHeader(void);
void displayWind(int x, int y, float angle, float windspeed, int radius);
void arrow(int x, int y, int asize, float aangle, int pwidth, int plength);
String windDegToDirection(float winddirection);
void drawStringMaxWidth(int x, int y, unsigned int text_width, String text, alignment align);
String titleCase(String text);
void displayWeatherDescription(int x, int y);
void displayWeatherPerson(int x, int y, String icon); 
void displayMoonPhase(int x, int y);
void displayPressureAndTrend(int x, int y, float pressure, String slope);
void displayRain(int x, int y);
String convertUnixTime(int unix_time);
double normalizedMoonPhase(int d, int m, int y);
void drawMoon(int x, int y, int dd, int mm, int yy, String hemisphere);
String moonPhase(int d, int m, int y, String hemisphere);
int julianDate(int d, int m, int y);
void displayWeatherForcast(int x, int y);
void displaySingleForecast(int x, int y, int offset, int index);
void displayWeatherIcon(int x, int y, String icon, bool large_size);
void addMoon (int x, int y, int scale);
void addSun(int x, int y, int scale, boolean icon_size);
void noData(int x, int y, bool large_size);
void sunnyIcon(int x, int y, bool large_size, String icon_name);
void mostlySunnyIcon(int x, int y, bool large_size, String icon_name);
void cloudyIcon(int x, int y, bool large_size, String icon_name);
void chanceOfRainIcon(int x, int y, bool large_size, String icon_name);
void rainIcon(int x, int y, bool large_size, String icon_name);
void thunderStormIcon(int x, int y, bool large_size, String icon_name);
void snowIcon(int x, int y, bool large_size, String icon_name);
void fogIcon(int x, int y, bool large_size, String icon_name);
void hazeIcon(int x, int y, bool large_size, String icon_name);
void addCloud(int x, int y, int scale, int linesize);
void addRain(int x, int y, int scale);
void addSnow(int x, int y, int scale);
void addThunderStorm(int x, int y, int scale);
void addFog(int x, int y, int scale, int linesize);